{...}: {
  imports = [
    ./blink-cmp.nix
    ./codediff.nix
    ./colorizer.nix
    ./conform-nvim.nix
    ./gitblame.nix
    ./gitsigns.nix
    ./guess-indent.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lint.nix
    ./lsp.nix
    ./lsp-lines.nix
    ./lsp-signature.nix
    ./lspsaga.nix
    ./lualine.nix
    ./mini.nix
    ./neogit.nix
    ./telescope.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trouble.nix
    ./undotree.nix
    ./web-devicons.nix
    ./which-key.nix
    ./yanky.nix
    ./yazi.nix
  ];
}
